### ISSUE TITLE
[bug] 初始化时出现报错导致后端无法正常启动

### ISSUE THREAD

**Issue by zhaomaoniu** [Yamamoto-2/tsugu-bangdream-bot#2]
## 环境
Node.js v18.16.1
npm v9.8.0
PM2 v5.3.0
backend f958c5aa9bee0a893d091592b218bdc7190a2e9d

## 可能的复现步骤
```
git clone https://github.com/Yamamoto-2/tsugu-bangdream-bot.git
cd tsugu-bangdream-bot/backend
npm install
pm2 start ecosystem.config.js
```

## 日志
PM2:
![image](https://github.com/Yamamoto-2/tsugu-bangdream-bot/assets/55650833/772978ca-67c6-4313-8a28-7906ccf8140b)

ts-node:
![image](https://github.com/Yamamoto-2/tsugu-bangdream-bot/assets/55650833/eb36310c-e08e-460c-953e-0436452e8054)

## 希望达到的效果
后端正常运行

**Comment by Yamamoto-2** [comment]
https://github.com/Yamamoto-2/tsugu-bangdream-bot/commit/d6c11b052a217550c6f63b01d3006a0782c4901c
