### ISSUE TITLE
获取资源时，url中的域名是否可以在配置中读取.

### ISSUE THREAD

**Issue by SuperGuGuGu** [Yamamoto-2/tsugu-bangdream-bot#5]
将资源改到从其他域名下载时，需要去查找并替换，而不可以在配置中统一替换。

(https://github.com/Yamamoto-2/tsugu-bangdream-bot/blob/f7cd0771be00d6810cb8397ce2b21f67d218285e/backend/src/types/Song.ts#L197)
![Snipaste_2024-06-01_17-09-39](https://github.com/Yamamoto-2/tsugu-bangdream-bot/assets/109544213/1f147b05-1408-4e21-b763-9e9ad488f66f)

**Comment by Yamamoto-2** [comment]
这是我设计的失误，之后会全部换成config.ts中的设置

**Comment by Yamamoto-2** [comment]
https://github.com/Yamamoto-2/tsugu-bangdream-bot/commit/d0ff4ea05145237e4a9b2f71647aa349e9eb730d
